package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Locator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from d:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u5/2488/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Tuesday, March 18, 2014 1:15:46 AM PDT
*/

public interface Locator extends LocatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Locator
